In [1]:
import pandas as pd
df=pd.read_csv("../data/raw/walmart_sales.csv")
df.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [5]:
df['Date']=pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[ns]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
 5   date          421570 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](2), float64(1), int64(2)
memory usage: 16.5 MB

In [6]:
df.duplicated().sum()

np.int64(0)

This shows that zero duplicated values by using duplicated function and sum.

In [12]:
df=df.sort_values(by='Date')
df.head()

        Store  Dept       Date  Weekly_Sales  IsHoliday
0           1     1 2010-02-05      24924.50      False
277665     29     5 2010-02-05      15552.08      False
277808     29     6 2010-02-05       3200.22      False
277951     29     7 2010-02-05      10820.05      False
278094     29     8 2010-02-05      20055.64      False

In [13]:
df=df.rename(columns={
    'Weekly_Sales':'weekly_sales',
    'IsHoliday':'is_holiday',
    'Store':'store_id',
    'Dept':'dept_id'
})
df.columns

Index(['store_id', 'dept_id', 'Date', 'weekly_sales', 'is_holiday'], dtype='object')

I used the renaming feature of pandas to rename the whole columns.

In [18]:
#Basic Sanity checks
df.isna().sum()
df.describe()

,store_id,dept_id,Date,weekly_sales
count,421570.000000,421570.000000,421570,421570.000000
mean,22.200546,44.260317,2011-06-18 08:30:31.963375360,15981.258123
min,1.000000,1.000000,2010-02-05 00:00:00,-4988.940000
25%,11.000000,18.000000,2010-10-08 00:00:00,2079.650000
50%,22.000000,37.000000,2011-06-17 00:00:00,7612.030000
75%,33.000000,74.000000,2012-02-24 00:00:00,20205.852500
max,45.000000,99.000000,2012-10-26 00:00:00,693099.360000
std,12.785297,30.492054,NaN,22711.183519

In [19]:
df.to_csv("../data/processed/cleaned_walmart_sales.csv", index=False)