In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/cleaned_walmart_sales.csv")
df['Date'] = pd.to_datetime(df['Date'])

df = df.sort_values(['store_id', 'dept_id', 'Date'])
df.head()

       store_id  dept_id       Date  weekly_sales  is_holiday
0             1        1 2010-02-05      24924.50       False
5747          1        1 2010-02-12      46039.49        True
6829          1        1 2010-02-19      41595.55       False
11698         1        1 2010-02-26      19403.54       False
12681         1        1 2010-03-05      21827.90       False

Here the sorting is done in this way

first sort on the basis of store_id->dept_id->date

In [3]:
#Time-based feature
df['year']=df['Date'].dt.year
df['month']=df['Date'].dt.month
df['week']=df['Date'].dt.isocalendar().week
df['day_of_week']=df['Date'].dt.dayofweek
df['quarter']=df['Date'].dt.quarter
df.head()

,store_id,dept_id,Date,weekly_sales,is_holiday,year,month,week,day_of_week,quarter
0,1,1,2010-02-05,24924.50,False,2010,2,5,4,1
5747,1,1,2010-02-12,46039.49,True,2010,2,6,4,1
6829,1,1,2010-02-19,41595.55,False,2010,2,7,4,1
11698,1,1,2010-02-26,19403.54,False,2010,2,8,4,1
12681,1,1,2010-03-05,21827.90,False,2010,3,9,4,1

By using this our model will undestand following:
1. Monthly Analytics
2. Weekly cycles
3. Quaterly trends

In [ ]:
#Lag Feature-what was sales last week
df['lag_1']=df.groupby(['store_id','dept_id'])['weekly_sales'].shift(1)
df['lag_2']=df.groupby(['store_id','dept_id'])['weekly_sales'].shift(2)
df['lag_4']=df.groupby(['store_id','dept_id'])['weekly_sales'].shift(4)